source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
platform :ios, '9.0'
target 'YLT_Kit_Example' do
  pod 'YLT_Kit', :path => '../'

  target 'YLT_Kit_Tests' do
    inherit! :search_paths

    
  end
end
